#!/usr/bin/env php
<?php

require_once 'CodeAnalyzer.php';

$code = (new \HfaTools\CodeAnalyzer($argv));

$reports = [
    'Model' => 'Models',
    'Controller' => 'Controllers',
    'Repo' => 'Repos',
    'Command' => 'Commands',
];

foreach ($reports as $rootNode => $title) {
    echo "===========\n";
    echo "$title\n";
    echo "===========\n";
    echo $code->diagram($rootNode)->report;
}
